### ISSUE TITLE
onIncominCall listener не срабатывает после app restart

### ISSUE THREAD

**Issue by ivanesi** [voximplant/flutter_voximplant#1]
При дебаге если рестартнуть приложение не срабатывает листенер `_client.onIncomingCall = _onIncomingCall;` 
Хотя в логах видно `I/VOXSDK  ( 9385): Invoke onIncomingCall`

Если остановить дебаг и включить заново то все ок.

**Comment by YuliaGrigorieva** [comment]
Добрый день!

Пожалуйста, уточните, что имеется в виду под "рестартнуть приложение"? Hod reload или что-то другое?

**Comment by ivanesi** [comment]
Нет при hot reload все норм.

Баг при hot restart. 
Кнопка Restart в дебагере vsCode : ![image](https://user-images.githubusercontent.com/8102865/66986216-0862fb80-f0f1-11e9-8d4b-7825843bf482.png)

Или Shift+r в терминале.

**Comment by AlaaEldeenYsr** [comment]
I'm facing the same issue, any updates ?

**Comment by VladimirBrejcha** [comment]
@AlaaEldeenYsr ,
We have researched this issue, it is most likely related to hot restart realisation.
According to [documentation](https://flutter.dev/docs/development/packages-and-plugins/using-packages#adding-a-package-dependency-to-an-app):
> If the package brings platform-specific code (Java/Kotlin for Android, Swift/Objective-C for iOS), that code must be built into your app. Hot reload and hot restart only update the Dart code, so a full restart of the app might be required to avoid errors like MissingPluginException when using the package.

Voximplant Flutter SDK have platform-specific code, so functionality like hot restart might not work correctly. I would recommend to use hot reload (as it does not rebuild the state but instead just injects updated source code) or full restart.
