### ISSUE TITLE
Flutter Audio Conference

### ISSUE THREAD

**Issue by FarhanAli001** [voximplant/flutter_voximplant#13]
I want to make an audio conference call flutter app using voximplant but didn't get anything useful, i have been working on this for week but still failed to do this, kindly help me to complete this task, i have already short of time, i will be very thankful to you if you help me

**Comment by YuliaGrigorieva** [comment]
Hello @FarhanAli001 !

Voximplant platform provides a lot of features and solutions.

Before implementing any solution, we recommend to take a look at the [Basic concepts](https://voximplant.com/docs/introduction/introduction_to_voximplant/basic_concepts) of the platform to understand how it works.

Unfortunately, we do not have the resources to implement the demo application for each type of solutions that can be done with the Voximplant platform.

If you have any specific questions, we can answer them and try to help to resolve the issues you face with.

Best regards,
Yulia Grigorieva
