### ISSUE TITLE
uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by Matthuffy** [voximplant/flutter_voximplant#14]
Note: /Users/Matt/.pub-cache/hosted/pub.dartlang.org/flutter_voximplant-2.2.0/android/src/main/java/com/voximplant/flutter_voximplant/ClientModule.java uses unchecked or unsafe operations.

**Comment by Matthuffy** [comment]
For now I am just @SuppressWarnings("unchecked") it for now as do not want customers seeing this when they attempt to compile

**Comment by YuliaGrigorieva** [comment]
Hello @Matthuffy !

Thank you for your report!
We will fix it in the next release.

Best regards,
Yulia Grigorieva

**Comment by Matthuffy** [comment]
For now I have just set @SuppressWarnings("unchecked") for that since it is only a warning.

**Comment by VladimirBrejcha** [comment]
Fixed in 2.3.0
