### ISSUE TITLE
Do you support background call on iOS and Android?

### ISSUE THREAD

**Issue by rafekun** [voximplant/flutter_voximplant#15]
Do you support background call on iOS and Android?
and, could you tell me the major limitations of current version.
Thanks

**Comment by YuliaGrigorieva** [comment]
Hello @rafekun ,

The SDK supports audio and video calls in the background, as well as push notifications.

The SDK currently does not support screen sharing, but we plan to add this functionality in next versions.
Could you please let me know the functionality you need, so I can confirm if it is supported or not?

Best regards,
Yulia Grigorieva

**Comment by rafekun** [comment]
@YuliaGrigorieva Thanks for your reply.
Since agora does not currently support audio calls on background, I was searching for alternative voip sdks.
I will try voximplant, and if it is good, I will use it for our production projects.
Regards
