### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by vmeretin** [voximplant/flutter_voximplant#18]
https://dart.dev/null-safety/migration-guide

**Comment by higorlapacw** [comment]
Any news on this? Since flutter 2.0.0, null-safety is pretty much required.

**Comment by joaovirgilicw** [comment]
Any update?

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for reaching out to us!

We are going to migrate to null-safety soon. ETA - early April.

Best regards,
Yulia Grigorieva

**Comment by VladimirBrejcha** [comment]
Released in 3.0!
