### ISSUE TITLE
Feature request: Quality issue listener

### ISSUE THREAD

**Issue by vmeretin** [voximplant/flutter_voximplant#35]
Please add this methods from native SDKs to Flutter SDK

https://voximplant.com/docs/references/iossdk/call/viqualityissuedelegate
https://voximplant.com/docs/references/androidsdk/call/iqualityissuelistener

**Comment by pe1ros** [comment]
Hello @vmeretin  !

We released new version [v3.5.0](https://github.com/voximplant/flutter_voximplant/releases/tag/v3.5.0) , you can using these APIs now

**Comment by vmeretin** [comment]
```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: type 'Null' is not a subtype of type 'VIQualityIssueLevel'
#0      new VIQualityIssue._fromMap (package:flutter_voximplant/src/call/quality_issue.dart:104:20)
#1      new VIPacketLoss._fromMap (package:flutter_voximplant/src/call/quality_issue.dart:237:15)
#2      _VICallQualityIssue._listener (package:flutter_voximplant/src/call/quality_issue.dart:350:51)
#3      _rootRunUnary (dart:async/zone.dart:1434:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#7      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
```

**Comment by pe1ros** [comment]
Hello @vmeretin 

Thanks for reporting the issue. We have just released a hotfix update - v3.5.1

**Comment by vmeretin** [comment]
And another one exception. It reproducing from time to time, not always

`MissingPluginException(No implementation found for method listen on channel plugins.voximplant.com/quality_issues_call_97AE837013A9446B.1656950491.120147780)`

**Comment by vmeretin** [comment]
We start listen qualityIssuesStream on `onIncomingCall` callback and after calling `call` method

**Comment by YuliaGrigorieva** [comment]
@vmeretin ,

May MissingPluginException be related to a hot reload?

Best regards,
Yulia Grigorieva

**Comment by vmeretin** [comment]
Yes, most likely it is due to hot reload. I don't see similar errors from production builds.
