### ISSUE TITLE
onEndpointAdded event on Android has null userName and displayName in v 3.4.0

### ISSUE THREAD

**Issue by babaev** [voximplant/flutter_voximplant#37]
Native implementation on Android puts userName and displayName with "endpoint" prefix in endpointAdded map, but ios version uses old notation

https://github.com/voximplant/flutter_voximplant/blob/66c78647458a09dfbf3ab3e334a5a7fa34571bb7/android/src/main/java/com/voximplant/flutter_voximplant/CallModule.java#L547

https://github.com/voximplant/flutter_voximplant/blob/66c78647458a09dfbf3ab3e334a5a7fa34571bb7/ios/Classes/VICallModule.m#L390

https://github.com/voximplant/flutter_voximplant/blob/66c78647458a09dfbf3ab3e334a5a7fa34571bb7/lib/src/call/call.dart#L637

**Comment by pe1ros** [comment]
Hello @babaev !

We released new version [v3.5.0](https://github.com/voximplant/flutter_voximplant/releases/tag/v3.5.0) , please update your app and report if the issue reproduced
