### ISSUE TITLE
Callback methods for Signaling: SEND, Signaling: onMessage events

### ISSUE THREAD

**Issue by EssamOmar1994** [voximplant/flutter_voximplant#4]
Hi,

I'm trying to handle background notification and i'm getting this message in the console:
I/VOXSDK  (13915): Signaling: onMessage: {"name" : "__pong" , "params" : []}
so is there any way to access the callback for this message?

**Comment by YuliaGrigorieva** [comment]
Hello @EssamOmar1994 ,

This message means that the client is connected to the Voximplant Cloud. This is an internal log of native Voximplant Android SDK and there is no way to get access to it.

Please provide more details about your problem, so we can give the recommendations.

Best regards,
Yulia Grigorieva

**Comment by zadcall** [comment]
Hello **@YuliaGrigorieva** 
I'm making a calling application and I'm trying to get the duration of the call but the isn't a clear way to get the duration in the SDK.

**Comment by YuliaGrigorieva** [comment]
Hello @zadcall,

I have move your qustion to a new issue as it is not related to the topic. Please see https://github.com/voximplant/flutter_voximplant/issues/5

Best regards,
Yulia Grigorieva

**Comment by zadcall** [comment]
Hello @YuliaGrigorieva 

Thank you for your response. i will close this issue now and follow the other issue :D

Best regards,
Essam Omar
