### ISSUE TITLE
Wrong Client State on IOS (not able to monitore real state of the client)

### ISSUE THREAD

**Issue by henriquetroiano** [voximplant/flutter_voximplant#43]
Hello Voximplant Team!
**_Note: This does NOT happens on Android._**

This bug is reproducible on fresh iOS Example!
The client stucks everytime on: "connecting" or "loggingin", never show me "connected" or "Logged", like on Android!
This is very critical for us, because on our function we check the client state before connect to the voximplant client and check if is connected before do a login, if not, I watch the client state change to the desired state to call the same function again.
We show to the final client the client state too, so now, this function is unavailable on iOS due to that.

Setup:
MacBook Pro (Retina, 13-inch, Early 2015) >> MacOS Monterey 12.3.1 (21E258);
Iphone 7 Plus >> iOS 15.4.1

Software Specs:
Flutter: Version 3.0.5 (x86)
Xcode: Version 13.3 (13E113)
VSCode: Version 1.30.2 (1.30.2)
Cocoapods: Version 1.11.2

Here I attached the entire flutter logs, in two versions: Regular and Verbose, choose the better one for the error analysis.
[flutter_run_regular.txt](https://github.com/voximplant/flutter_voximplant/files/9690285/flutter_run_regular.txt)
[flutter_run_verbose.txt](https://github.com/voximplant/flutter_voximplant/files/9690286/flutter_run_verbose.txt)

And the call logs (?) >> I think this is not necessary, but attaching anyway.
[call_logs.txt](https://github.com/voximplant/flutter_voximplant/files/9690304/call_logs.txt)

As you can see, I could be able to receive and call even if I'm on Reconnecting State.

Thanks in advance.

**Comment by YuliaGrigorieva** [comment]
Hello @henriquetroiano 

We have found the issue and working on the fix.

We will notify you as soon as a new version with the fix is released

Best regards,
Yulia Grigorieva

**Comment by henriquetroiano** [comment]
Hello @YuliaGrigorieva 
Any update on this ?

**Comment by YuliaGrigorieva** [comment]
Hello @henriquetroiano 

We have just released Voximplant Flutter SDK 3.6.0 with the fix.
Please update the sdk version and let me know if you face with any issues.

Best regards,
Yulia Grigorieva

**Comment by henriquetroiano** [comment]
Hello @YuliaGrigorieva 
The error was successfully fixed on 3.6.0. Closing the issue.
Thank you
