### ISSUE TITLE
Backgrounded or Terminated iOS App "Destination number is unavailable"

### ISSUE THREAD

**Issue by henriquetroiano** [voximplant/flutter_voximplant#44]
Hello,

This issue is reproducible with the demo app!
_**Note: This does NOT happens on Android.**_

When we close or minimize the app, the call is rejected with the error "Destination number is unavailable". Doesn't matter if I register the token for push notifications or not.
When I minimize or close the app, the "onConnectionClosed is called". Maybe this behavior is expected, but the "Destination number is unavailable" is not expected.

Here is attached them both logs (flutter and call log) in two cases:
_Explanation: the call_logs_1_done.txt file is the call I did with the app open: I receive, accept and let the call running for around 10s. Then I minimize the app with home iOS button and call again, with no success, this is the call_logs_2_unavailable.txt file._

1. With the example app **without registering** push notifications >> 
[flutter_run_verbose.txt](https://github.com/voximplant/flutter_voximplant/files/9690749/flutter_run_verbose.txt)
[call_logs_1_done.txt](https://github.com/voximplant/flutter_voximplant/files/9690750/call_logs_1_done.txt)
[call_logs_2_unavailable.txt](https://github.com/voximplant/flutter_voximplant/files/9690751/call_logs_2_unavailable.txt)

2. With the example app **registering** push notification >>  
[flutter_run_verbose.txt](https://github.com/voximplant/flutter_voximplant/files/9690764/flutter_run_verbose.txt)
[call_logs_1_done.txt](https://github.com/voximplant/flutter_voximplant/files/9690766/call_logs_1_done.txt)
[call_logs_2_unavailable.txt](https://github.com/voximplant/flutter_voximplant/files/9690768/call_logs_2_unavailable.txt)
Note: In this case, I just updated the call_service.dart from example to include the token registration, with no success. I do not did any change on the code, just the token registration. Here is the screenshot of the line I changed: 
<img width="1070" alt="Captura de Tela 2022-10-01 às 13 35 15" src="https://user-images.githubusercontent.com/63327237/193419516-6604aaaf-eec6-48fd-8a80-7e0083fb2d46.png">

**_Looking deep at the logs, them both says "push certificate not found", so, I think that the regsiterForPushNotifications function is not working properly on iOS._**

Setup:
MacBook Pro (Retina, 13-inch, Early 2015) >> MacOS Monterey 12.3.1 (21E258);
Iphone 7 Plus >> iOS 15.4.1

Software Specs:
Flutter: Version 3.0.5 (x86)
Xcode: Version 13.3 (13E113)
VSCode: Version 1.30.2 (1.30.2)
Cocoapods: Version 1.11.2

Maybe, this issue is related to the other one I created: #43 

Thanks in advance,

**Comment by YesVladess** [comment]
Hello, first of all, due to iOS specific we cannot maintain connection to Vox Platform while being in background mode, so after entering background "onConnectionClosed" event is expected.

For your main issue, it seems from the screenshot, that you are trying to register firebase token, which are not supported for iOS. We recommend you to switch to any library that supports registering token from PushKit Apple framework.

**Comment by henriquetroiano** [comment]
hello, @YesVladess .
Yes, Firebase Token is currently supported by iOS and we already use it on our project. Is not supported by voximplant??

**Comment by henriquetroiano** [comment]
We are perfectly able to use firebase tokens on iOS and perform notifications on the target phone. Is is not a push notification with payload ?

**Comment by YuliaGrigorieva** [comment]
Hello @henriquetroiano 

For iOS Push notification Voximplant platform communicates directly with APNS (Apple Servers) and does not use Firebase platform.

Moreover, for VoIP calls Voximplant platform sends a special type of Apple push notificaitons - VoIP pushes that are not supported by Firebase.

So, to get push notifications about incoming calls on iOS platform you need:
- use any 3rd party package that provides the API for PushKit Apple framework
- obtain a voip push token and register it to the Voximplant SDK
- handle VoIP notification from PushKit Apple framework
- integrate CallKit Apple framework as per Apple requirement for VoIP notifications

Best regards,
Yulia Grigorieva

**Comment by henriquetroiano** [comment]
Ok, all done. Now, how can I integrate your callkit to the VIClient ???
The fresh example does not contain any example of integration from flutter_callkit_voximplant and flutter_voximplant. So I can't handle if I accepted or declined on the iOS side.

**Comment by henriquetroiano** [comment]
This is the only thing (except bug #43 ) that left on the app. The android app is OK!
Can you help us with this integration?

**Comment by YuliaGrigorieva** [comment]
Hello @henriquetroiano 

Yes, you can take a look at our demo projects, especially at 
- https://github.com/voximplant/flutter_demos/blob/master/audio_call/lib/services/call/callkit_service.dart for CallKit integration
- https://github.com/voximplant/flutter_demos/blob/master/audio_call/lib/services/push/push_service_ios.dart  for PushKit integration

Best regards,
Yulia Grigorieva
