### ISSUE TITLE
callId

### ISSUE THREAD

**Issue by zadcall** [voximplant/flutter_voximplant#7]
Is there is any way to get the call id from the push notification payload ?! @YuliaGrigorieva

**Comment by zadcall** [comment]
@VladimirBrejcha I was hoping the with the last update you handle the push notification too, or add something to get the callId so that we can handle it our self without the whole issues we have.

**Comment by VladimirBrejcha** [comment]
@zadcall, callId can be received from the [onIncomingCall](https://voximplant.com/docs/references/fluttersdk/client/viclient#onincomingcall) after reporting push to the client via [handlePushNotification](https://voximplant.com/docs/references/fluttersdk/client/viclient#handlepushnotification).
So, basically your flow will be like this:
1. Receive push
2. Report push to VIClient
3. Receive onIncomingCall (includes VICall instance for the push)
4. Work with received VICall
