### ISSUE TITLE
How to fix webrtc bitcode for flutter iOS

### ISSUE THREAD

**Issue by Anmol92verma** [voximplant/flutter_voximplant#9]
How do i fix bitcode issues for webrtc as mentioned on this link https://voximplant.com/docs/references/iossdk/bitcode for Flutter builds ?

Thanks!

**Comment by YuliaGrigorieva** [comment]
Hello @Anmol92verma !

You should download bitcode builds for Voximplant IOS SDK and Voximplant WebRTC SDK of the versions indicated in the podspec of the Voximplant Flutter SDK you use. See: https://github.com/voximplant/flutter_voximplant/blob/cb2aef0f88ad9c91ce62aa937a03ff3f655b914e/ios/flutter_voximplant.podspec#L18

Then, you should modify Podfile of your Flutter application by adding these lines:
```
pod 'VoxImplantSDK', :path => 'Path/To/VoxImplant_bitcode/'
pod 'VoxImplantWebRTC', :path => 'Path/To/VoxImplantWebRTC_bitcode/'
```
and replace `Path/To/VoxImplant_bitcode/` and `Path/To/VoxImplantWebRTC_bitcode/` with the paths to the frameworks downloaded.

After, please run `pod install`.

Please let me know if you face any issues.

Best regards,
Yulia Grigorieva

**Comment by Anmol92verma** [comment]
It helped! Thanks @YuliaGrigorieva
